print('Enter 1st number:')
a=int(input())
print('Enter 2nd number:')
b=int(input())
print('The addition of two numbers is:',a+b)
print('The differnce of two numbers is:',a-b)
print('The product of two numbers is:',a*b)
print('The division of two numbers is:',a//b)
print('The modulus of two numbers is:',a%b)
print('The  power of two numbers is:',a**b)

